#include "simulation/game_interface/simulation_game_engine_player.hpp"

REFERENCE_DECLARE(0x0189B110, c_simulation_game_engine_player_entity_definition, g_simulation_game_engine_player_entity_definition);

