#pragma once

#include "cseries/cseries.hpp"

enum e_session_game_start_status
{
	_session_game_start_status_none = 0,
	_session_game_start_status_not_pregame,
	_session_game_start_status_changing_settings_member,
	_session_game_start_status_join_in_progress,
	_session_game_start_status_loading,
	_session_game_start_status_ready_leader,
	_session_game_start_status_accelerate_countdown,
	_session_game_start_status_countdown,
	_session_game_start_status_error,

	k_session_game_start_status_count
};

enum e_session_game_start_error
{
	_session_game_start_error_none = 0,
	_session_game_start_error_network_configuration_unavailable,
	_session_game_start_error_banhammer_unavailable,
	_session_game_start_error_player_stats_unavailable,
	_session_game_start_match_error_master_hopper_file_unavailable,
	_session_game_start_match_error_hopper_specific_file_unavailable,
	_session_game_start_error_network_configuration_pending,
	_session_game_start_error_banhammer_pending,
	_session_game_start_error_player_stats_pending,
	_session_game_start_match_error_master_hopper_file_pending,
	_session_game_start_match_error_hopper_specific_file_pending,
	_session_game_start_error_no_map_selected,
	_session_game_start_error_map_load_failure,
	_session_game_start_error_map_load_precaching,
	_session_game_start_error_invalid_film_selected,
	_session_game_start_error_no_film_selected,
	_session_game_start_error_too_many_teams,
	_session_game_start_error_all_players_are_observers,
	_session_game_start_error_too_many_local_players_for_coop,
	_session_game_start_error_too_many_players_for_network_coop,
	_session_game_start_error_players_incompatible_for_network_coop,
	_session_game_start_error_account_not_online_enabled,
	_session_game_start_match_error_must_have_online_enabled_profiles_for_match,
	_session_game_start_match_error_must_connect_to_live_for_match,
	_session_game_start_match_error_must_have_live_for_match,
	_session_game_start_match_error_invalid_hopper,
	_session_game_start_match_error_squad_too_large,
	_session_game_start_match_error_squad_too_small,
	_session_game_start_match_error_games_played_too_low,
	_session_game_start_match_error_games_played_too_high,
	_session_game_start_match_error_experience_too_low,
	_session_game_start_match_error_experience_too_high,
	_session_game_start_match_error_access_bit_not_set,
	_session_game_start_match_error_unpaid_in_paid_hopper,
	_session_game_start_match_error_paid_in_unpaid_hopper,
	_session_game_start_match_error_player_not_in_required_region,
	_session_game_start_match_error_player_not_in_required_country_code,
	_session_game_start_match_error_player_not_in_required_language,
	_session_game_start_match_error_player_not_in_required_gamerzone,
	_session_game_start_match_error_guest_player_when_not_allowed,
	_session_game_start_match_error_not_beta_player_in_beta_hopper,
	_session_game_start_match_error_player_missing_content,
	_session_game_start_match_error_player_missing_files,
	_session_game_start_match_error_player_missing_required_maps,
	_session_game_start_match_error_player_banned_from_matchmaking,
	_session_game_start_match_error_not_yet_start_time,
	_session_game_start_match_error_end_time_has_passed,
	_session_game_start_error_custom_games_are_disabled_for_alpha,
	_session_game_start_error_maximum_multiplayer_split_screen_exceeded,
	_session_game_start_error_must_be_connected_to_live_in_live_lobby,
	_session_game_start_error_must_be_connected_to_live_for_alpha,
	_session_game_start_error_only_one_player_allowed_in_theater_for_alpha,
	_session_game_start_error_film_too_many_players,
	_session_game_start_error_film_harddrive_required,
	_session_game_start_error_film_party_leader_requirement,
	_session_game_start_error_film_all_players_not_compatible,
	_session_game_start_error_forge_too_many_players,
	_session_game_start_error_user_content_not_permitted,
	_session_game_start_match_error_coop_player_missing_hdd,
	_session_game_start_match_error_coop_player_hdd_mismatch,
	_session_game_start_match_error_coop_player_language_mismatch,
	_session_game_start_match_error_invalid_film_selected_language,
	_session_game_start_error_signedin_controller_detatched,

	k_session_game_start_error_count
};

extern long __cdecl user_interface_squad_get_countdown_delaying_player();
extern long __cdecl user_interface_squad_get_countdown_timer();
extern e_session_game_start_status __cdecl user_interface_get_session_game_start_status(e_session_game_start_error* error, dword* player_error_mask);
