#pragma once

#define BOT_CLIENT(true_false) if (game_is_bot_client() == true_false)

enum e_session_creation_flags
{
	_session_creation_unknown_bit0 = 0,
	_session_creation_unknown_bit1,
	_session_creation_unknown_bit2,
	_session_creation_unknown_bit3,

	k_number_of_session_creation_flags
};

enum e_input_user_index
{
	_input_user_index0 = 0,
	_input_user_index1,
	_input_user_index2,
	_input_user_index3,

	k_number_of_input_users,

	k_input_user_none = -1
};

enum e_output_user_index
{
	_output_user_index0 = 0,
	_output_user_index1,
	_output_user_index2,
	_output_user_index3,

	k_number_of_output_users,

	k_output_user_none = -1
};

enum e_network_game_type
{
	_network_game_type_none = 0,
	_network_game_type_custom_game,
	_network_game_type_matchmaking,
	_network_game_type_film,

	k_network_game_type_count
};

enum e_desired_multiplayer_mode
{
	_desired_multiplayer_mode_none = -1,
	_desired_multiplayer_mode_campaign,
	_desired_multiplayer_mode_custom_game,
	_desired_multiplayer_mode_matchmaking,
	_desired_multiplayer_mode_film,

	k_number_of_desired_multiplayer_modes
};

enum e_session_game_mode
{
	_session_game_mode_none = 0,
	_session_game_mode_matchmaking,
	_session_game_mode_pregame,
	_session_game_mode_ingame,
	_session_game_mode_postgame,

	k_session_game_mode_count
};

enum e_gui_game_mode
{
	_ui_game_mode_none = -1,
	_ui_game_mode_campaign,
	_ui_game_mode_matchmaking,
	_ui_game_mode_multiplayer,
	_ui_game_mode_map_editor,
	_ui_game_mode_theater,
	_ui_game_mode_survival,

	k_ui_game_mode_count
};

enum e_game_mode
{
	_game_mode_none = 0,
	_game_mode_campaign,
	_game_mode_multiplayer,
	_game_mode_mainmenu,
	_game_mode_shared,

	k_game_mode_count
};

enum e_campaign_difficulty_level
{
	_campaign_difficulty_level_easy = 0,
	_campaign_difficulty_level_normal,
	_campaign_difficulty_level_heroic,
	_campaign_difficulty_level_legendary,

	k_number_of_campaign_difficulty_levels
};

// e_game_skulls
enum e_primary_skulls
{
	_campaign_skull_iron = 0,
	_campaign_skull_black_eye,
	_campaign_skull_tough_luck,
	_campaign_skull_catch,
	_campaign_skull_fog,
	_campaign_skull_famine,
	_campaign_skull_thunderstorm,
	_campaign_skull_tilt,
	_campaign_skull_mythic,

	k_number_of_primary_skulls
};

enum e_secondary_skulls
{
	_campaign_skull_assassin = 0,
	_campaign_skull_blind,
	_campaign_skull_superman,
	_campaign_skull_birthday_party,
	_campaign_skull_daddy,
	_campaign_skull_third_person,
	_campaign_skull_directors_cut,

	k_number_of_secondary_skulls
};

// #TODO: find a home
enum e_game_simulation_type
{
	_game_simulation_none = 0,
	_game_simulation_local,
	_game_simulation_synchronous_client,
	_game_simulation_synchronous_server,
	_game_simulation_distributed_client,
	_game_simulation_distributed_server,

	k_game_simulation_count
};

enum e_network_game_simulation_protocol
{
	_network_game_simulation_none = 0,
	_network_game_simulation_local,
	_network_game_simulation_sync_client,
	_network_game_simulation_sync_server,
	_network_game_simulation_dist_client,
	_network_game_simulation_dist_server,

	k_network_game_simulation_count
};

// #TODO: find a home
enum e_game_playback_type
{
	_game_playback_none = 0,
	_game_playback_local,
	_game_playback_network_server,
	_game_playback_network_client,

	k_game_playback_count
};

enum e_content_item_type
{

};

enum e_player_model_choice
{
	_player_model_choice_spartan,
	_player_model_choice_elite,

	k_number_of_player_model_choices
};

#define VALID_CONTROLLER(CONTROLLER) ((CONTROLLER) >= _controller_index0 && (CONTROLLER) < k_number_of_controllers)

enum e_controller_index
{
	_controller_index0 = 0,
	_controller_index1,
	_controller_index2,
	_controller_index3,

	k_number_of_controllers,

	k_any_controller = 0xFF,
	k_no_controller = 0xFFFFFFFF,
};

enum e_window_index
{
	_window_index0 = 0,
	_window_index1,
	_window_index2,
	_window_index3,
	_window_index4,

	k_number_of_render_windows,

	k_any_window = 0xFF,
	k_no_window = 0xFFFFFFFF,
};

enum e_network_game_start_mode
{
	_network_game_start_mode_campaign = 0,
	_network_game_start_mode_custom_game,
	_network_game_start_mode_matchmaking,
	_network_game_start_mode_film,

	k_number_of_network_game_start_modes
};

enum e_network_join_queue_mode
{
	_network_join_closed_to_all_joins = 0,
	_network_join_open_to_join_squad,
	_network_join_queue_joins_to_group,
	_network_join_process_queued_group_joins,
	_network_join_queue_closed_while_in_match,

	k_network_join_queue_mode_count
};

enum e_join_local_state
{
	_join_local_state_none = 0,
	_join_local_state_start_join_squad,
	_join_local_state_joining_squad,
	_join_local_state_leaving_old_squad,
	_join_local_state_processing_join_to_us,

	k_join_local_state_count
};

enum e_join_remote_state
{
	_join_remote_state_none = 0,
	_join_remote_state_party_start_join,
	_join_remote_state_party_join_host,
	_join_remote_state_party_join_clients,
	_join_remote_state_party_leave_old_squad,
	_join_remote_state_party_join_complete,
	_join_remote_state_leave_group,

	k_join_remote_state_count
};

enum e_join_type
{
	_join_type_squad = 0,
	_join_type_group,

	k_join_type_count
};

enum e_networking_join_destination_squad
{
	_join_destination_unknown0 = 0,

	k_join_destination_count
};

enum e_transport_platform
{
	_transport_platform_unknown0 = 0,
	_transport_platform_unknown1,

	k_transport_platform_count
};

enum e_network_channel_closure_reason
{
	_network_channel_reason_none = 0,
	_network_channel_reason_link_destroyed,
	_network_channel_reason_link_refused_listen,
	_network_channel_reason_channel_deleted,
	_network_channel_reason_connect_timeout,
	_network_channel_reason_connect_refused,
	_network_channel_reason_connect_reinitiate,
	_network_channel_reason_establish_timeout,
	_network_channel_reason_address_change,
	_network_channel_reason_destination_unreachable,
	_network_channel_reason_remote_closure,
	_network_channel_reason_connection_overflow,
	_network_channel_reason_message_overflow,
	_network_channel_reason_security_lost,
	_network_channel_reason_observer_released,
	_network_channel_reason_observer_refused,
	_network_channel_reason_observer_timeout,
	_network_channel_reason_observer_reset,
	_network_channel_reason_observer_reset_security,
	_network_channel_reason_test,

	k_network_channel_reason_count
};

enum e_network_join_refuse_reason
{
	_network_join_refuse_reason_none = 0,
	_network_join_refuse_reason_tried_to_join_self,
	_network_join_refuse_reason_could_not_connect,
	_network_join_refuse_reason_join_timed_out,
	_network_join_refuse_reason_not_found,
	_network_join_refuse_reason_privacy_mode,
	_network_join_refuse_reason_not_joinable,
	_network_join_refuse_reason_session_full,
	_network_join_refuse_reason_alpha_split_screen,
	_network_join_refuse_reason_session_disband,
	_network_join_refuse_reason_session_booted,
	_network_join_refuse_reason_address_invalid,
	_network_join_refuse_reason_address_failed,
	_network_join_refuse_reason_too_many_observers,
	_network_join_refuse_reason_aborted,
	_network_join_refuse_reason_abort_ignored,
	_network_join_refuse_reason_wrong_payload_type,
	_network_join_refuse_reason_no_reservation,
	_network_join_refuse_reason_in_matchmaking,
	_network_join_refuse_reason_player_count_zero,
	_network_join_refuse_reason_player_not_online_enabled,
	_network_join_refuse_reason_player_add_pending,
	_network_join_refuse_reason_player_add_failed,
	_network_join_refuse_reason_host_time_out,
	_network_join_refuse_reason_rejected_by_host,
	_network_join_refuse_reason_peer_version_too_low,
	_network_join_refuse_reason_host_version_too_low,
	_network_join_refuse_reason_holding_in_queue,
	_network_join_refuse_reason_film_in_progress,
	_network_join_refuse_reason_campaign_in_progress,
	_network_join_refuse_reason_user_content_not_allowed,
	_network_join_refuse_reason_survival_in_progress,
	_network_join_refuse_reason_executable_type_mismatch,

	k_network_join_refuse_reason_count,
};

enum e_network_session_boot_reason
{
	_network_session_boot_reason_player_booted_player,
	_network_session_boot_reason_unknown1,
	_network_session_boot_reason_failed_to_load_map,
	_network_session_boot_reason_write_stats_grief_time,
	_network_session_boot_reason_unknown4,
	_network_session_boot_reason_unknown5,
	_network_session_boot_reason_recreating_session,
	_network_session_boot_reason_join_aborted,
	_network_session_boot_reason_simulation_aborted,
	_network_session_boot_reason_unknown9,
	_network_session_boot_reason_unknown10,
	_network_session_boot_reason_unknown11,
	_network_session_boot_reason_unknown12,

	k_network_session_boot_reason_count
};

enum e_life_cycle_join_result
{
	_life_cycle_join_result_none = 0,
	_life_cycle_join_result_join_in_progress,
	_life_cycle_join_result_join_failed_generic_error,
	_life_cycle_join_result_join_failed_to_find_session,
	_life_cycle_join_result_join_failed_not_enough_space,
	_life_cycle_join_result_join_failed_game_not_open,
	_life_cycle_join_result_join_failed_target_is_matchmaking,
	_life_cycle_join_result_join_failed_host_timed_out,
	_life_cycle_join_result_join_failed_peer_version_too_low,
	_life_cycle_join_result_join_failed_host_version_too_low,
	_life_cycle_join_result_join_failed_unable_to_connect_open_nat,
	_life_cycle_join_result_join_failed_unable_to_connect_moderate_nat,
	_life_cycle_join_result_join_failed_unable_to_connect_closed_nat,
	_life_cycle_join_result_join_failed_unable_to_connect_party_open_nat,
	_life_cycle_join_result_join_failed_unable_to_connect_party_moderate_nat,
	_life_cycle_join_result_join_failed_unable_to_connect_party_strict_nat,
	_life_cycle_join_result_join_failed_party_member_not_online_enabled,
	_life_cycle_join_result_join_failed_film_in_progress,
	_life_cycle_join_result_join_failed_campaign_in_progress,
	_life_cycle_join_result_join_failed_user_content_not_permitted,
	_life_cycle_join_result_join_failed_survival_in_progress,
	_life_cycle_join_result_join_failed_invalid_executable_type,

	k_life_cycle_join_result_count
};

enum e_network_session_type
{
	_network_session_type_none = 0,
	_network_session_type_squad,
	_network_session_type_group,

	k_network_session_type_count
};

enum e_network_session_class
{
	_network_session_class_offline = 0,
	_network_session_class_system_link,
	_network_session_class_xbox_live,

	k_network_session_class_count
};

enum e_network_session_mode
{
	_network_session_mode_none = 0,
	_network_session_mode_idle,
	_network_session_mode_setup,
	_network_session_mode_in_game,
	_network_session_mode_end_game,
	_network_session_mode_post_game,
	_network_session_mode_matchmaking_start,
	_network_session_mode_matchmaking_searching,
	_network_session_mode_matchmaking_gathering,
	_network_session_mode_matchmaking_slave,
	_network_session_mode_matchmaking_disbanding,
	_network_session_mode_matchmaking_arbitrating,
	_network_session_mode_matchmaking_choosing_game,

	k_network_session_mode_count
};

enum e_matchmaking_search_preference
{
};

enum e_life_cycle_state
{
	_life_cycle_state_none = 0,
	_life_cycle_state_pre_game,
	_life_cycle_state_start_game,
	_life_cycle_state_in_game,
	_life_cycle_state_end_game_write_stats,
	_life_cycle_state_leaving,
	_life_cycle_state_joining,
	_life_cycle_state_matchmaking_start,
	_life_cycle_state_matchmaking_find_match_client,
	_life_cycle_state_matchmaking_find_match,
	_life_cycle_state_matchmaking_find_and_assemble_match,
	_life_cycle_state_matchmaking_assemble_match,
	_life_cycle_state_matchmaking_select_host,
	_life_cycle_state_matchmaking_arbitration,
	_life_cycle_state_matchmaking_prepare_map,
	_life_cycle_state_in_match,
	_life_cycle_state_end_match_write_stats,
	_life_cycle_state_post_match,

	k_life_cycle_state_count,
};

enum e_life_cycle_matchmaking_progress_type
{
	_life_cycle_matchmaking_progress_type_unknown0 = 0,
	_life_cycle_matchmaking_progress_type_searching_for_match,
	_life_cycle_matchmaking_progress_type_assembling_match,
	_life_cycle_matchmaking_progress_type_unknown3,
	_life_cycle_matchmaking_progress_type_configuring_match,
	_life_cycle_matchmaking_progress_type_post_match,

	k_life_cycle_matchmaking_progress_type_count
};

enum e_network_rough_quality
{
};

enum e_session_game_start_status
{
	_session_game_start_status_none = 0,
	_session_game_start_status_not_pregame,
	_session_game_start_status_changing_settings_member,
	_session_game_start_status_join_in_progress,
	_session_game_start_status_loading,
	_session_game_start_status_ready_leader,
	_session_game_start_status_accelerate_countdown,
	_session_game_start_status_countdown,
	_session_game_start_status_error,

	k_session_game_start_status_count
};

enum e_session_game_start_error
{
	_session_game_start_error_none = 0,
	_session_game_start_error_network_configuration_unavailable,
	_session_game_start_error_banhammer_unavailable,
	_session_game_start_error_player_stats_unavailable,
	_session_game_start_match_error_master_hopper_file_unavailable,
	_session_game_start_match_error_hopper_specific_file_unavailable,
	_session_game_start_error_network_configuration_pending,
	_session_game_start_error_banhammer_pending,
	_session_game_start_error_player_stats_pending,
	_session_game_start_match_error_master_hopper_file_pending,
	_session_game_start_match_error_hopper_specific_file_pending,
	_session_game_start_error_no_map_selected,
	_session_game_start_error_map_load_failure,
	_session_game_start_error_map_load_precaching,
	_session_game_start_error_invalid_film_selected,
	_session_game_start_error_no_film_selected,
	_session_game_start_error_too_many_teams,
	_session_game_start_error_all_players_are_observers,
	_session_game_start_error_too_many_local_players_for_coop,
	_session_game_start_error_too_many_players_for_network_coop,
	_session_game_start_error_players_incompatible_for_network_coop,
	_session_game_start_error_account_not_online_enabled,
	_session_game_start_match_error_must_have_online_enabled_profiles_for_match,
	_session_game_start_match_error_must_connect_to_live_for_match,
	_session_game_start_match_error_must_have_live_for_match,
	_session_game_start_match_error_invalid_hopper,
	_session_game_start_match_error_squad_too_large,
	_session_game_start_match_error_squad_too_small,
	_session_game_start_match_error_games_played_too_low,
	_session_game_start_match_error_games_played_too_high,
	_session_game_start_match_error_experience_too_low,
	_session_game_start_match_error_experience_too_high,
	_session_game_start_match_error_access_bit_not_set,
	_session_game_start_match_error_unpaid_in_paid_hopper,
	_session_game_start_match_error_paid_in_unpaid_hopper,
	_session_game_start_match_error_player_not_in_required_region,
	_session_game_start_match_error_player_not_in_required_country_code,
	_session_game_start_match_error_player_not_in_required_language,
	_session_game_start_match_error_player_not_in_required_gamerzone,
	_session_game_start_match_error_guest_player_when_not_allowed,
	_session_game_start_match_error_not_beta_player_in_beta_hopper,
	_session_game_start_match_error_player_missing_content,
	_session_game_start_match_error_player_missing_files,
	_session_game_start_match_error_player_missing_required_maps,
	_session_game_start_match_error_player_banned_from_matchmaking,
	_session_game_start_match_error_not_yet_start_time,
	_session_game_start_match_error_end_time_has_passed,
	_session_game_start_error_custom_games_are_disabled_for_alpha,
	_session_game_start_error_maximum_multiplayer_split_screen_exceeded,
	_session_game_start_error_must_be_connected_to_live_in_live_lobby,
	_session_game_start_error_must_be_connected_to_live_for_alpha,
	_session_game_start_error_only_one_player_allowed_in_theater_for_alpha,
	_session_game_start_error_film_too_many_players,
	_session_game_start_error_film_harddrive_required,
	_session_game_start_error_film_party_leader_requirement,
	_session_game_start_error_film_all_players_not_compatible,
	_session_game_start_error_forge_too_many_players,
	_session_game_start_error_user_content_not_permitted,
	_session_game_start_match_error_coop_player_missing_hdd,
	_session_game_start_match_error_coop_player_hdd_mismatch,
	_session_game_start_match_error_coop_player_language_mismatch,
	_session_game_start_match_error_invalid_film_selected_language,
	_session_game_start_error_signedin_controller_detatched,

	k_session_game_start_error_count
};

enum e_network_session_map_status
{
	_network_session_map_status_none = 0,
	_network_session_map_status_failed,
	_network_session_map_status_precaching,
	_network_session_map_status_precached,
	_network_session_map_status_loaded,

	k_network_session_map_status_count
};

enum e_network_session_peer_state
{
	_network_session_peer_state_none = 0,
	_network_session_peer_state_rejoining,
	_network_session_peer_state_reserved,
	_network_session_peer_state_disconnected,
	_network_session_peer_state_connected,
	_network_session_peer_state_joining,
	_network_session_peer_state_joined,
	_network_session_peer_state_waiting,
	_network_session_peer_state_established,

	k_network_session_peer_state_count
};

enum e_gui_network_session_advertisement_mode
{
	_gui_network_session_advertisement_mode_invalid = 0xFFFFFFFF,
	_gui_network_session_advertisement_mode_open_to_public,
	_gui_network_session_advertisement_mode_open_to_friends,
	_gui_network_session_advertisement_mode_invite_only,
	_gui_network_session_advertisement_mode_system_link,
	_gui_network_session_advertisement_mode_offline,
	_gui_network_session_advertisement_mode_full,

	k_gui_network_session_advertisement_mode_count
};

enum e_user_interface_session_leave_type
{
	_user_interface_session_leave_type_leave_to_pre_game_lobby = 0,
	_user_interface_session_leave_type_leave_to_main_menu,

	k_user_interface_session_leave_type_count
};

enum e_user_interface_session_leave_reason
{
	_user_interface_session_leave_reason_all_controllers_signed_out = 0,
	_user_interface_session_leave_reason_booted,
	_user_interface_session_leave_reason_failed_to_start,
	_user_interface_session_leave_reason_leaving_game,
	_user_interface_session_leave_reason_backing_out_of_searching,
	_user_interface_session_leave_reason_backing_out_of_post_game,
	_user_interface_session_leave_reason_backing_out_of_pre_game,

	// Halo: Reach
	//_user_interface_session_leave_reason_whitelist_enforcement,
	//_user_interface_session_leave_reason_leaving_game_on_resume,

	// MCC
	//_user_interface_session_leave_reason_banned,

	k_user_interface_session_leave_reason_count
};

enum e_network_session_peer_properties_status_flags
{
	_network_session_peer_properties_status_game_stats_written_bit = 0,
	_network_session_peer_properties_status_match_ready_to_start_bit,
	_network_session_peer_properties_status_match_arbitration_succeeded_bit,
	_network_session_peer_properties_status_match_arbitration_failed_bit,
	_network_session_peer_properties_status_match_teams_selected_bit,
	_network_session_peer_properties_status_match_repeated_play_set_bit,
	_network_session_peer_properties_status_match_started_bit,
	_network_session_peer_properties_status_match_start_failed_bit,
	_network_session_peer_properties_status_match_initial_stats_written_bit,
	_network_session_peer_properties_status_match_initial_stats_write_failed_bit,
	_network_session_peer_properties_status_match_stats_written_bit,
	_network_session_peer_properties_status_match_host_selection_complete_bit,
	_network_session_peer_properties_status_match_post_match_countdown_bit,
	_network_session_peer_properties_status_match_idle_controller_bit,
	_network_session_peer_properties_status_match_ready_for_next_match_bit,
	_network_session_peer_properties_status_match_simulation_aborted_bit,
	_network_session_peer_properties_status_match_acknowledge_sync_bit,

	k_network_session_peer_properties_status_flags
};

enum e_ui_message_type
{
	_ui_message_type_unknown0 = 0,
	_ui_message_type_controller_input,
	_ui_message_type_xenon,
	_ui_message_type_load_screen,
	_ui_message_type_unknown4,
	_ui_message_type_screen_custom,
	_ui_message_type_dialog_result,
	_ui_message_type_unknown7,
};

enum e_browser_type
{
	// names from string ids used with `<browser-title` game tag parser data function

	_browser_type_system_link_games = 0,
	_browser_type_friends_games,
	_browser_type_xbox_live_games,

	k_browser_type_count
};

enum e_game_progression_level
{
	_game_progression_level_none = 0,
	_game_progression_level_normal,
	_game_progression_level_hub_and_level_is_hub,
	_game_progression_level_spoke_and_level_is_spoke,

	k_game_progression_level_count
};

enum e_achievement
{
	_achievement_beat_sc100 = 0,
	_achievement_beat_sc110,
	_achievement_beat_sc120,
	_achievement_beat_sc130,
	_achievement_beat_sc140,
	_achievement_beat_sc150,
	_achievement_beat_l200,
	_achievement_beat_l300,
	_achievement_beat_campaign_normal,
	_achievement_beat_campaign_heroic,
	_achievement_beat_campaign_legendary,
	_achievement_wraith_killer,
	_achievement_naughty_naughty,
	_achievement_good_samaritan,
	_achievement_dome_inspector,
	_achievement_laser_blaster,
	_achievement_both_tubes,
	_achievement_i_like_fire,
	_achievement_my_clothes,
	_achievement_pink_and_deadly,
	_achievement_dark_times,
	_achievement_trading_down,
	_achievement_headcase,
	_achievement_boom_headshot,
	_achievement_ewww_sticky,
	_achievement_junior_detective,
	_achievement_gumshoe,
	_achievement_super_sleuth,
	_achievement_metagame_points_in_sc100,
	_achievement_metagame_points_in_sc110,
	_achievement_metagame_points_in_sc120,
	_achievement_metagame_points_in_sc130a,
	_achievement_metagame_points_in_sc130b,
	_achievement_metagame_points_in_sc140,
	_achievement_metagame_points_in_l200,
	_achievement_metagame_points_in_l300,
	_achievement_be_like_marty,
	_achievement_find_all_audio_logs,
	_achievement_find_01_audio_logs,
	_achievement_find_03_audio_logs,
	_achievement_find_15_audio_logs,
	_achievement_vidmaster_challenge_deja_vu,
	_achievement_vidmaster_challenge_endure,
	_achievement_vidmaster_challenge_classic,
	_achievement_heal_up,
	_achievement_stunning,
	_achievement_tourist,

	k_achievement_count
};

enum e_damage_reporting_type
{
	_damage_reporting_type_unknown = 0,
	_damage_reporting_type_guardians,
	_damage_reporting_type_falling_damage,
	_damage_reporting_type_generic_collision_damage,
	_damage_reporting_type_armor_lock_crush,
	_damage_reporting_type_generic_melee_damage,
	_damage_reporting_type_generic_explosion,
	_damage_reporting_type_magnum_pistol,
	_damage_reporting_type_plasma_pistol,
	_damage_reporting_type_needler,
	_damage_reporting_type_excavator,
	_damage_reporting_type_smg,
	_damage_reporting_type_plasma_rifle,
	_damage_reporting_type_battle_rifle,
	_damage_reporting_type_carbine,
	_damage_reporting_type_shotgun,
	_damage_reporting_type_sniper_rifle,
	_damage_reporting_type_beam_rifle,
	_damage_reporting_type_assault_rifle,
	_damage_reporting_type_spike_rifle,
	_damage_reporting_type_flak_cannon,
	_damage_reporting_type_missile_launcher,
	_damage_reporting_type_rocket_launcher,
	_damage_reporting_type_spartan_laser,
	_damage_reporting_type_brute_shot,
	_damage_reporting_type_flame_thrower,
	_damage_reporting_type_sentinal_gun,
	_damage_reporting_type_energy_sword,
	_damage_reporting_type_gravity_hammer,
	_damage_reporting_type_frag_grenade,
	_damage_reporting_type_plasma_grenade,
	_damage_reporting_type_claymore_grenade,
	_damage_reporting_type_firebomb_grenade,
	_damage_reporting_type_flag_melee_damage,
	_damage_reporting_type_bomb_melee_damage,
	_damage_reporting_type_bomb_explosion_damage,
	_damage_reporting_type_ball_melee_damage,
	_damage_reporting_type_human_turret,
	_damage_reporting_type_plasma_cannon,
	_damage_reporting_type_plasma_mortar,
	_damage_reporting_type_plasma_turret,
	_damage_reporting_type_shade_turret,
	_damage_reporting_type_banshee,
	_damage_reporting_type_ghost,
	_damage_reporting_type_mongoose,
	_damage_reporting_type_scorpion,
	_damage_reporting_type_scorpion_gunner,
	_damage_reporting_type_spectre_driver,
	_damage_reporting_type_spectre_gunner,
	_damage_reporting_type_warthog_driver,
	_damage_reporting_type_warthog_gunner,
	_damage_reporting_type_warthog_gunner_gauss,
	_damage_reporting_type_wraith,
	_damage_reporting_type_wraith_anti_infantry,
	_damage_reporting_type_tank,
	_damage_reporting_type_chopper,
	_damage_reporting_type_hornet,
	_damage_reporting_type_mantis,
	_damage_reporting_type_mauler,
	_damage_reporting_type_sentinel_beam,
	_damage_reporting_type_sentinel_rpg,
	_damage_reporting_type_teleporter,
	_damage_reporting_type_prox_mine,
	_damage_reporting_type_marksman_rifle,

	k_damage_reporting_type_count
};

enum e_interface_font
{
	_interface_font_terminal = 0,
	_interface_font_body_text,
	_interface_font_title,
	_interface_font_super_large_font,
	_interface_font_large_body_text,
	_interface_font_split_screen_hud_message,
	_interface_font_full_screen_hud_message,
	_interface_font_english_body_text,
	_interface_font_HUD_number_text,
	_interface_font_subtitle_font,
	_interface_font_main_menu_font,

	k_interface_font_count
};

enum e_game_engine_category
{
	_game_engine_category_game_base_misc = 0,
	_game_engine_category_game_base_respawn,
	_game_engine_category_game_base_social,
	_game_engine_category_game_base_map,

	_game_engine_category_base_player_traits,
	_game_engine_category_base_player_traits_shields,
	_game_engine_category_base_player_traits_weapons,
	_game_engine_category_base_player_traits_movement,
	_game_engine_category_base_player_traits_sensors,
	_game_engine_category_base_player_traits_appearance,
	_game_engine_category_base_player_templated,

	_game_engine_category_respawntraits_traits,
	_game_engine_category_respawntraits_traits_shields,
	_game_engine_category_respawntraits_traits_weapons,
	_game_engine_category_respawntraits_traits_movement,
	_game_engine_category_respawntraits_traits_sensors,
	_game_engine_category_respawntraits_traits_appearance,
	_game_engine_category_respawntraits_templated,

	_game_engine_category_red_powerup_traits,
	_game_engine_category_red_powerup_traits_shields,
	_game_engine_category_red_powerup_traits_weapons,
	_game_engine_category_red_powerup_traits_movement,
	_game_engine_category_red_powerup_traits_sensors,
	_game_engine_category_red_powerup_traits_appearance,
	_game_engine_category_red_powerup_templated,

	_game_engine_category_blue_powerup_traits,
	_game_engine_category_blue_powerup_traits_shields,
	_game_engine_category_blue_powerup_traits_weapons,
	_game_engine_category_blue_powerup_traits_movement,
	_game_engine_category_blue_powerup_traits_sensors,
	_game_engine_category_blue_powerup_traits_appearance,
	_game_engine_category_blue_powerup_templated,

	_game_engine_category_yellow_powerup_traits,
	_game_engine_category_yellow_powerup_traits_shields,
	_game_engine_category_yellow_powerup_traits_weapons,
	_game_engine_category_yellow_powerup_traits_movement,
	_game_engine_category_yellow_powerup_traits_sensors,
	_game_engine_category_yellow_powerup_traits_appearance,
	_game_engine_category_yellow_powerup_templated,

	_game_engine_category_powerup_duration,

	_game_engine_category_slayer_leader_traits,
	_game_engine_category_slayer_leader_traits_shields,
	_game_engine_category_slayer_leader_traits_weapons,
	_game_engine_category_slayer_leader_traits_movement,
	_game_engine_category_slayer_leader_traits_sensors,
	_game_engine_category_slayer_leader_traits_appearance,
	_game_engine_category_slayer_leader_templated,

	_game_engine_category_oddball_carrier_traits,
	_game_engine_category_oddball_carrier_traits_shields,
	_game_engine_category_oddball_carrier_traits_weapons,
	_game_engine_category_oddball_carrier_traits_movement,
	_game_engine_category_oddball_carrier_traits_sensors,
	_game_engine_category_oddball_carrier_traits_appearance,
	_game_engine_category_oddball_carrier_templated,

	_game_engine_category_assult_carrier_traits,
	_game_engine_category_assult_carrier_traits_shields,
	_game_engine_category_assult_carrier_traits_weapons,
	_game_engine_category_assult_carrier_traits_movement,
	_game_engine_category_assult_carrier_traits_sensors,
	_game_engine_category_assult_carrier_traits_appearance,
	_game_engine_category_assult_carrier_templated,

	_game_engine_category_ctf_carrier_traits,
	_game_engine_category_ctf_carrier_traits_shields,
	_game_engine_category_ctf_carrier_traits_weapons,
	_game_engine_category_ctf_carrier_traits_movement,
	_game_engine_category_ctf_carrier_traits_sensors,
	_game_engine_category_ctf_carrier_traits_appearance,
	_game_engine_category_ctf_carrier_templated,

	_game_engine_category_juggernaut_traits,
	_game_engine_category_juggernaut_traits_shields,
	_game_engine_category_juggernaut_traits_weapons,
	_game_engine_category_juggernaut_traits_movement,
	_game_engine_category_juggernaut_traits_sensors,
	_game_engine_category_juggernaut_traits_appearance,
	_game_engine_category_juggernaut_templated,

	_game_engine_category_king_hill_traits,
	_game_engine_category_king_hill_traits_shields,
	_game_engine_category_king_hill_traits_weapons,
	_game_engine_category_king_hill_traits_movement,
	_game_engine_category_king_hill_traits_sensors,
	_game_engine_category_king_hill_traits_appearance,
	_game_engine_category_king_hill_templated,

	_game_engine_category_zombie_traits,
	_game_engine_category_zombie_traits_shields,
	_game_engine_category_zombie_traits_weapons,
	_game_engine_category_zombie_traits_movement,
	_game_engine_category_zombie_traits_sensors,
	_game_engine_category_zombie_traits_appearance,
	_game_engine_category_zombie_templated,

	_game_engine_category_1st_zombie_traits,
	_game_engine_category_1st_zombie_traits_shields,
	_game_engine_category_1st_zombie_traits_weapons,
	_game_engine_category_1st_zombie_traits_movement,
	_game_engine_category_1st_zombie_traits_sensors,
	_game_engine_category_1st_zombie_traits_appearance,
	_game_engine_category_1st_zombie_templated,

	_game_engine_category_safe_haven_traits,
	_game_engine_category_safe_haven_traits_shields,
	_game_engine_category_safe_haven_traits_weapons,
	_game_engine_category_safe_haven_traits_movement,
	_game_engine_category_safe_haven_traits_sensors,
	_game_engine_category_safe_haven_traits_appearance,
	_game_engine_category_safe_haven_templated,

	_game_engine_category_last_human_traits,
	_game_engine_category_last_human_traits_shields,
	_game_engine_category_last_human_traits_weapons,
	_game_engine_category_last_human_traits_movement,
	_game_engine_category_last_human_traits_sensors,
	_game_engine_category_last_human_traits_appearance,
	_game_engine_category_last_human_templated,

	_game_engine_category_target_dummy_traits,
	_game_engine_category_target_dummy_traits_shields,
	_game_engine_category_target_dummy_traits_weapons,
	_game_engine_category_target_dummy_traits_movement,
	_game_engine_category_target_dummy_traits_sensors,
	_game_engine_category_target_dummy_traits_appearance,
	_game_engine_category_target_dummy_templated,

	_game_engine_category_territory_defender_traits,
	_game_engine_category_territory_defender_traits_shields,
	_game_engine_category_territory_defender_traits_weapons,
	_game_engine_category_territory_defender_traits_movement,
	_game_engine_category_territory_defender_traits_sensors,
	_game_engine_category_territory_defender_traits_appearance,
	_game_engine_category_territory_defender_templated,

	_game_engine_category_territory_attacker_traits,
	_game_engine_category_territory_attacker_traits_shields,
	_game_engine_category_territory_attacker_traits_weapons,
	_game_engine_category_territory_attacker_traits_movement,
	_game_engine_category_territory_attacker_traits_sensors,
	_game_engine_category_territory_attacker_traits_appearance,
	_game_engine_category_territory_attacker_templated,

	_game_engine_category_vip_team_traits,
	_game_engine_category_vip_team_traits_shields,
	_game_engine_category_vip_team_traits_weapons,
	_game_engine_category_vip_team_traits_movement,
	_game_engine_category_vip_team_traits_sensors,
	_game_engine_category_vip_team_traits_appearance,
	_game_engine_category_vip_team_templated,

	_game_engine_category_vip_influence_traits,
	_game_engine_category_vip_influence_traits_shields,
	_game_engine_category_vip_influence_traits_weapons,
	_game_engine_category_vip_influence_traits_movement,
	_game_engine_category_vip_influence_traits_sensors,
	_game_engine_category_vip_influence_traits_appearance,
	_game_engine_category_vip_influence_templated,

	_game_engine_category_vip_traits,
	_game_engine_category_vip_traits_shields,
	_game_engine_category_vip_traits_weapons,
	_game_engine_category_vip_traits_movement,
	_game_engine_category_vip_traits_sensors,
	_game_engine_category_vip_traits_appearance,
	_game_engine_category_vip_templated,

	_game_engine_category_sandbox_editor_traits,
	_game_engine_category_sandbox_editor_traits_shields,
	_game_engine_category_sandbox_editor_traits_weapons,
	_game_engine_category_sandbox_editor_traits_movement,
	_game_engine_category_sandbox_editor_traits_sensors,
	_game_engine_category_sandbox_editor_traits_appearance,
	_game_engine_category_sandbox_editor_templated,

	_game_engine_category_ctf_top_level_options,
	_game_engine_category_slayer_top_level_options,
	_game_engine_category_oddball_top_level_options,
	_game_engine_category_king_top_level_options,
	_game_engine_category_sandbox_top_level_options,
	_game_engine_category_juggernaut_top_level_options,
	_game_engine_category_territories_top_level_options,
	_game_engine_category_assault_top_level_options,
	_game_engine_category_infection_top_level_options,
	_game_engine_category_vip_top_level_options,
	_game_engine_category_training_top_level_options,

	_game_engine_category_map_override_advanced_options,

	_game_engine_category_respawn_advanced_options,
	_game_engine_category_respawn_modifiers,

	_game_engine_category_slayer_primary_options,
	_game_engine_category_slayer_advanced_options,
	_game_engine_category_slayer_scoring_options,

	_game_engine_category_oddball_primary_options,
	_game_engine_category_oddball_advanced_options,

	_game_engine_category_assault_primary_options,
	_game_engine_category_assault_advanced_options,

	_game_engine_category_ctf_primary_options,
	_game_engine_category_ctf_advanced_options,

	_game_engine_category_juggernaut_primary_options,
	_game_engine_category_juggernaut_advanced_options,

	_game_engine_category_king_primary_options,
	_game_engine_category_king_advanced_options,

	_game_engine_category_infection_primary_options,
	_game_engine_category_infection_advanced_options,
	_game_engine_category_infection_scoring_options,

	_game_engine_category_target_training_primary_options,
	_game_engine_category_training_advanced_options,

	_game_engine_category_target_1_setup,
	_game_engine_category_target_2_setup,
	_game_engine_category_target_3_setup,
	_game_engine_category_target_4_setup,
	_game_engine_category_target_5_setup,
	_game_engine_category_target_6_setup,
	_game_engine_category_target_7_setup,
	_game_engine_category_target_8_setup,
	_game_engine_category_target_9_setup,
	_game_engine_category_target_10_setup,

	_game_engine_category_vip_primary_options,
	_game_engine_category_vip_advanced_options,

	_game_engine_category_territories_primary_options,
	_game_engine_category_territories_advanced_options,

	_game_engine_category_player_template_traits,
	_game_engine_category_player_template_traits_shields,
	_game_engine_category_player_template_traits_weapons,
	_game_engine_category_player_template_traits_movement,
	_game_engine_category_player_template_traits_sensors,
	_game_engine_category_player_template_traits_appearance,

	_game_engine_category_player_alternate_template_traits,
	_game_engine_category_player_alternate_template_traits_shields,
	_game_engine_category_player_alternate_template_traits_weapons,
	_game_engine_category_player_alternate_template_traits_movement,
	_game_engine_category_player_alternate_template_traits_sensors,
	_game_engine_category_player_alternate_template_traits_appearance,

	k_game_engine_category_count
};

enum e_game_variant_parameter
{
	_game_variant_parameter_game_misc_teams = 0,
	_game_variant_parameter_game_misc_director_allow_player_switching,
	_game_variant_parameter_game_misc_round_reset_map,
	_game_variant_parameter_game_misc_round_time_limit,
	_game_variant_parameter_game_misc_round_limit,
	_game_variant_parameter_game_misc_early_win_count,

	_game_variant_parameter_game_respawn_inherit_timer,
	_game_variant_parameter_game_respawn_with_teammate,
	_game_variant_parameter_game_respawn_at_location,
	_game_variant_parameter_game_respawn_on_kill,
	_game_variant_parameter_game_respawn_lives_per_round,
	_game_variant_parameter_game_respawn_team_lives_per_round,
	_game_variant_parameter_game_respawn_respawn_time,
	_game_variant_parameter_game_respawn_suicide_penalty,
	_game_variant_parameter_game_respawn_betrayal_penalty,
	_game_variant_parameter_game_respawn_growth,
	_game_variant_parameter_game_respawn_traits_duration,

	_game_variant_parameter_respawn_shield_damage_resistance,
	_game_variant_parameter_respawn_shield_multiplier,
	_game_variant_parameter_respawn_shield_recharge_rate,
	_game_variant_parameter_respawn_headshot_immunity,
	_game_variant_parameter_respawn_vampirism,
	_game_variant_parameter_respawn_damage_modifier_percentage,
	_game_variant_parameter_respawn_initial_primary_weapon,
	_game_variant_parameter_respawn_initial_secondary_weapon,
	_game_variant_parameter_respawn_initial_grenade_count,
	_game_variant_parameter_respawn_recharging_grenades,
	_game_variant_parameter_respawn_infinite_ammo,
	_game_variant_parameter_respawn_weapon_pickup,
	_game_variant_parameter_respawn_walking_speed,
	_game_variant_parameter_respawn_personal_gravity,
	_game_variant_parameter_respawn_vehicle_use,
	_game_variant_parameter_respawn_motion_tracker,
	_game_variant_parameter_respawn_motion_tracker_range,
	_game_variant_parameter_respawn_waypoint,
	_game_variant_parameter_respawn_active_camo,
	_game_variant_parameter_respawn_visual,
	_game_variant_parameter_respawn_forced_change_colors,

	_game_variant_parameter_game_social_observers,
	_game_variant_parameter_game_social_team_changing,
	_game_variant_parameter_game_social_friendly_fire,
	_game_variant_parameter_game_social_betrayal_booting,
	_game_variant_parameter_game_social_enemy_voice,
	_game_variant_parameter_game_social_open_channel_voice,
	_game_variant_parameter_game_social_dead_player_voice,

	_game_variant_parameter_game_map_grenades,
	_game_variant_parameter_game_map_indestructible_vehicles,

	_game_variant_parameter_player_shield_damage_resistance,
	_game_variant_parameter_player_shield_multiplier,
	_game_variant_parameter_player_shield_recharge_rate,
	_game_variant_parameter_player_headshot_immunity,
	_game_variant_parameter_player_vampirism,
	_game_variant_parameter_player_damage_modifier_percentage,
	_game_variant_parameter_player_initial_primary_weapon,
	_game_variant_parameter_player_initial_secondary_weapon,
	_game_variant_parameter_player_initial_grenade_count,
	_game_variant_parameter_player_recharging_grenades,
	_game_variant_parameter_player_infinite_ammo,
	_game_variant_parameter_player_weapon_pickup,
	_game_variant_parameter_player_walking_speed,
	_game_variant_parameter_player_personal_gravity,
	_game_variant_parameter_player_vehicle_use,
	_game_variant_parameter_player_motion_tracker,
	_game_variant_parameter_player_motion_tracker_range,
	_game_variant_parameter_player_waypoint,
	_game_variant_parameter_player_active_camo,
	_game_variant_parameter_player_visual,
	_game_variant_parameter_player_forced_change_colors,

	_game_variant_parameter_game_map_weapon_set,
	_game_variant_parameter_game_map_vehicle_set,

	_game_variant_parameter_red_powerup_shield_damage_resistance,
	_game_variant_parameter_red_powerup_shield_multiplier,
	_game_variant_parameter_red_powerup_shield_recharge_rate,
	_game_variant_parameter_red_powerup_headshot_immunity,
	_game_variant_parameter_red_powerup_vampirism,
	_game_variant_parameter_red_powerup_damage_modifier_percentage,
	_game_variant_parameter_red_powerup_initial_primary_weapon,
	_game_variant_parameter_red_powerup_initial_secondary_weapon,
	_game_variant_parameter_red_powerup_initial_grenade_count,
	_game_variant_parameter_red_powerup_recharging_grenades,
	_game_variant_parameter_red_powerup_infinite_ammo,
	_game_variant_parameter_red_powerup_weapon_pickup,
	_game_variant_parameter_red_powerup_walking_speed,
	_game_variant_parameter_red_powerup_personal_gravity,
	_game_variant_parameter_red_powerup_vehicle_use,
	_game_variant_parameter_red_powerup_motion_tracker,
	_game_variant_parameter_red_powerup_motion_tracker_range,
	_game_variant_parameter_red_powerup_waypoint,
	_game_variant_parameter_red_powerup_active_camo,
	_game_variant_parameter_red_powerup_visual,
	_game_variant_parameter_red_powerup_forced_change_colors,

	_game_variant_parameter_blue_powerup_shield_damage_resistance,
	_game_variant_parameter_blue_powerup_shield_multiplier,
	_game_variant_parameter_blue_powerup_shield_recharge_rate,
	_game_variant_parameter_blue_powerup_headshot_immunity,
	_game_variant_parameter_blue_powerup_vampirism,
	_game_variant_parameter_blue_powerup_damage_modifier_percentage,
	_game_variant_parameter_blue_powerup_initial_primary_weapon,
	_game_variant_parameter_blue_powerup_initial_secondary_weapon,
	_game_variant_parameter_blue_powerup_initial_grenade_count,
	_game_variant_parameter_blue_powerup_recharging_grenades,
	_game_variant_parameter_blue_powerup_infinite_ammo,
	_game_variant_parameter_blue_powerup_weapon_pickup,
	_game_variant_parameter_blue_powerup_walking_speed,
	_game_variant_parameter_blue_powerup_personal_gravity,
	_game_variant_parameter_blue_powerup_vehicle_use,
	_game_variant_parameter_blue_powerup_motion_tracker,
	_game_variant_parameter_blue_powerup_motion_tracker_range,
	_game_variant_parameter_blue_powerup_waypoint,
	_game_variant_parameter_blue_powerup_active_camo,
	_game_variant_parameter_blue_powerup_visual,
	_game_variant_parameter_blue_powerup_forced_change_colors,

	_game_variant_parameter_yellow_powerup_shield_damage_resistance,
	_game_variant_parameter_yellow_powerup_shield_multiplier,
	_game_variant_parameter_yellow_powerup_shield_recharge_rate,
	_game_variant_parameter_yellow_powerup_headshot_immunity,
	_game_variant_parameter_yellow_powerup_vampirism,
	_game_variant_parameter_yellow_powerup_damage_modifier_percentage,
	_game_variant_parameter_yellow_powerup_initial_primary_weapon,
	_game_variant_parameter_yellow_powerup_initial_secondary_weapon,
	_game_variant_parameter_yellow_powerup_initial_grenade_count,
	_game_variant_parameter_yellow_powerup_recharging_grenades,
	_game_variant_parameter_yellow_powerup_infinite_ammo,
	_game_variant_parameter_yellow_powerup_weapon_pickup,
	_game_variant_parameter_yellow_powerup_walking_speed,
	_game_variant_parameter_yellow_powerup_personal_gravity,
	_game_variant_parameter_yellow_powerup_vehicle_use,
	_game_variant_parameter_yellow_powerup_motion_tracker,
	_game_variant_parameter_yellow_powerup_motion_tracker_range,
	_game_variant_parameter_yellow_powerup_waypoint,
	_game_variant_parameter_yellow_powerup_active_camo,
	_game_variant_parameter_yellow_powerup_visual,
	_game_variant_parameter_yellow_powerup_forced_change_colors,

	_game_variant_parameter_game_map_red_powerup_duration,
	_game_variant_parameter_game_map_blue_powerup_duration,
	_game_variant_parameter_game_map_yellow_powerup_duration,

	_game_variant_parameter_slayer_team_scoring,
	_game_variant_parameter_slayer_score_to_win,
	_game_variant_parameter_slayer_kill_points,
	_game_variant_parameter_slayer_assist_points,
	_game_variant_parameter_slayer_death_points,
	_game_variant_parameter_slayer_suicide_points,
	_game_variant_parameter_slayer_betrayal_points,
	_game_variant_parameter_slayer_leader_killed_points,
	_game_variant_parameter_slayer_elimination_points,
	_game_variant_parameter_slayer_assassination_points,
	_game_variant_parameter_slayer_headshot_points,
	_game_variant_parameter_slayer_melee_points,
	_game_variant_parameter_slayer_sticky_points,
	_game_variant_parameter_slayer_splatter_points,
	_game_variant_parameter_slayer_killing_spree_points,

	_game_variant_parameter_slayer_leader_shield_damage_resistance,
	_game_variant_parameter_slayer_leader_shield_multiplier,
	_game_variant_parameter_slayer_leader_shield_recharge_rate,
	_game_variant_parameter_slayer_leader_headshot_immunity,
	_game_variant_parameter_slayer_leader_vampirism,
	_game_variant_parameter_slayer_leader_damage_modifier_percentage,
	_game_variant_parameter_slayer_leader_initial_primary_weapon,
	_game_variant_parameter_slayer_leader_initial_secondary_weapon,
	_game_variant_parameter_slayer_leader_initial_grenade_count,
	_game_variant_parameter_slayer_leader_recharging_grenades,
	_game_variant_parameter_slayer_leader_infinite_ammo,
	_game_variant_parameter_slayer_leader_weapon_pickup,
	_game_variant_parameter_slayer_leader_walking_speed,
	_game_variant_parameter_slayer_leader_personal_gravity,
	_game_variant_parameter_slayer_leader_vehicle_use,
	_game_variant_parameter_slayer_leader_motion_tracker,
	_game_variant_parameter_slayer_leader_motion_tracker_range,
	_game_variant_parameter_slayer_leader_waypoint,
	_game_variant_parameter_slayer_leader_active_camo,
	_game_variant_parameter_slayer_leader_visual,
	_game_variant_parameter_slayer_leader_forced_change_colors,

	_game_variant_parameter_oddball_auto_ball_pickup,
	_game_variant_parameter_oddball_ball_effect,
	_game_variant_parameter_oddball_team_scoring,
	_game_variant_parameter_oddball_waypoints,
	_game_variant_parameter_oddball_score_to_win,
	_game_variant_parameter_oddball_carrying_points,
	_game_variant_parameter_oddball_kill_points,
	_game_variant_parameter_oddball_ball_kill_points,
	_game_variant_parameter_oddball_carrier_kill_points,
	_game_variant_parameter_oddball_ball_count,
	_game_variant_parameter_oddball_ball_spawn_delay,
	_game_variant_parameter_oddball_inactive_respawn_delay,

	_game_variant_parameter_oddball_carrier_shield_damage_resistance,
	_game_variant_parameter_oddball_carrier_shield_multiplier,
	_game_variant_parameter_oddball_carrier_shield_recharge_rate,
	_game_variant_parameter_oddball_carrier_headshot_immunity,
	_game_variant_parameter_oddball_carrier_vampirism,
	_game_variant_parameter_oddball_carrier_damage_modifier_percentage,
	_game_variant_parameter_oddball_carrier_initial_primary_weapon,
	_game_variant_parameter_oddball_carrier_initial_secondary_weapon,
	_game_variant_parameter_oddball_carrier_initial_grenade_count,
	_game_variant_parameter_oddball_carrier_recharging_grenades,
	_game_variant_parameter_oddball_carrier_infinite_ammo,
	_game_variant_parameter_oddball_carrier_weapon_pickup,
	_game_variant_parameter_oddball_carrier_walking_speed,
	_game_variant_parameter_oddball_carrier_personal_gravity,
	_game_variant_parameter_oddball_carrier_vehicle_use,
	_game_variant_parameter_oddball_carrier_motion_tracker,
	_game_variant_parameter_oddball_carrier_motion_tracker_range,
	_game_variant_parameter_oddball_carrier_waypoint,
	_game_variant_parameter_oddball_carrier_active_camo,
	_game_variant_parameter_oddball_carrier_visual,
	_game_variant_parameter_oddball_carrier_forced_change_colors,

	_game_variant_parameter_ctf_touch_return_timeout,
	_game_variant_parameter_ctf_flag_at_home_to_score,
	_game_variant_parameter_ctf_bomb_sticky_arming,
	_game_variant_parameter_ctf_home_flag_waypoint,
	_game_variant_parameter_ctf_enemy_bomb_waypoint,
	_game_variant_parameter_ctf_game_type,
	_game_variant_parameter_ctf_respawn,
	_game_variant_parameter_ctf_score_to_win,
	_game_variant_parameter_ctf_sudden_death_time,
	_game_variant_parameter_ctf_flag_reset_time,
	_game_variant_parameter_ctf_bomb_arming_time,
	_game_variant_parameter_ctf_bomb_fuse_time,

	_game_variant_parameter_ctf_carrier_shield_damage_resistance,
	_game_variant_parameter_ctf_carrier_shield_multiplier,
	_game_variant_parameter_ctf_carrier_shield_recharge_rate,
	_game_variant_parameter_ctf_carrier_headshot_immunity,
	_game_variant_parameter_ctf_carrier_vampirism,
	_game_variant_parameter_ctf_carrier_damage_modifier_percentage,
	_game_variant_parameter_ctf_carrier_initial_primary_weapon,
	_game_variant_parameter_ctf_carrier_initial_secondary_weapon,
	_game_variant_parameter_ctf_carrier_initial_grenade_count,
	_game_variant_parameter_ctf_carrier_recharging_grenades,
	_game_variant_parameter_ctf_carrier_infinite_ammo,
	_game_variant_parameter_ctf_carrier_weapon_pickup,
	_game_variant_parameter_ctf_carrier_walking_speed,
	_game_variant_parameter_ctf_carrier_personal_gravity,
	_game_variant_parameter_ctf_carrier_vehicle_use,
	_game_variant_parameter_ctf_carrier_motion_tracker,
	_game_variant_parameter_ctf_carrier_motion_tracker_range,
	_game_variant_parameter_ctf_carrier_waypoint,
	_game_variant_parameter_ctf_carrier_active_camo,
	_game_variant_parameter_ctf_carrier_visual,
	_game_variant_parameter_ctf_carrier_forced_change_colors,

	_game_variant_parameter_infection_respawn_on_haven_move,
	_game_variant_parameter_infection_safe_haven_setting,
	_game_variant_parameter_infection_next_zombie,
	_game_variant_parameter_infection_initial_zombie_count,
	_game_variant_parameter_infection_safe_haven_movement_time,
	_game_variant_parameter_infection_zombie_kill_points,
	_game_variant_parameter_infection_points,
	_game_variant_parameter_infection_safe_haven_arrive_points,
	_game_variant_parameter_infection_suicide_points,
	_game_variant_parameter_infection_betrayal_points,
	_game_variant_parameter_infection_last_man_standing_bonus_points,

	_game_variant_parameter_zombie_shield_damage_resistance,
	_game_variant_parameter_zombie_shield_multiplier,
	_game_variant_parameter_zombie_shield_recharge_rate,
	_game_variant_parameter_zombie_headshot_immunity,
	_game_variant_parameter_zombie_vampirism,
	_game_variant_parameter_zombie_damage_modifier_percentage,
	_game_variant_parameter_zombie_initial_primary_weapon,
	_game_variant_parameter_zombie_initial_secondary_weapon,
	_game_variant_parameter_zombie_initial_grenade_count,
	_game_variant_parameter_zombie_recharging_grenades,
	_game_variant_parameter_zombie_infinite_ammo,
	_game_variant_parameter_zombie_weapon_pickup,
	_game_variant_parameter_zombie_walking_speed,
	_game_variant_parameter_zombie_personal_gravity,
	_game_variant_parameter_zombie_vehicle_use,
	_game_variant_parameter_zombie_motion_tracker,
	_game_variant_parameter_zombie_motion_tracker_range,
	_game_variant_parameter_zombie_waypoint,
	_game_variant_parameter_zombie_active_camo,
	_game_variant_parameter_zombie_visual,
	_game_variant_parameter_zombie_forced_change_colors,

	_game_variant_parameter_1st_zombie_shield_damage_resistance,
	_game_variant_parameter_1st_zombie_shield_multiplier,
	_game_variant_parameter_1st_zombie_shield_recharge_rate,
	_game_variant_parameter_1st_zombie_headshot_immunity,
	_game_variant_parameter_1st_zombie_vampirism,
	_game_variant_parameter_1st_zombie_damage_modifier_percentage,
	_game_variant_parameter_1st_zombie_initial_primary_weapon,
	_game_variant_parameter_1st_zombie_initial_secondary_weapon,
	_game_variant_parameter_1st_zombie_initial_grenade_count,
	_game_variant_parameter_1st_zombie_recharging_grenades,
	_game_variant_parameter_1st_zombie_infinite_ammo,
	_game_variant_parameter_1st_zombie_weapon_pickup,
	_game_variant_parameter_1st_zombie_walking_speed,
	_game_variant_parameter_1st_zombie_personal_gravity,
	_game_variant_parameter_1st_zombie_vehicle_use,
	_game_variant_parameter_1st_zombie_motion_tracker,
	_game_variant_parameter_1st_zombie_motion_tracker_range,
	_game_variant_parameter_1st_zombie_waypoint,
	_game_variant_parameter_1st_zombie_active_camo,
	_game_variant_parameter_1st_zombie_visual,
	_game_variant_parameter_1st_zombie_forced_change_colors,

	_game_variant_parameter_haven_defender_shield_damage_resistance,
	_game_variant_parameter_haven_defender_shield_multiplier,
	_game_variant_parameter_haven_defender_shield_recharge_rate,
	_game_variant_parameter_haven_defender_headshot_immunity,
	_game_variant_parameter_haven_defender_vampirism,
	_game_variant_parameter_haven_defender_damage_modifier_percentage,
	_game_variant_parameter_haven_defender_initial_primary_weapon,
	_game_variant_parameter_haven_defender_initial_secondary_weapon,
	_game_variant_parameter_haven_defender_initial_grenade_count,
	_game_variant_parameter_haven_defender_recharging_grenades,
	_game_variant_parameter_haven_defender_infinite_ammo,
	_game_variant_parameter_haven_defender_weapon_pickup,
	_game_variant_parameter_haven_defender_walking_speed,
	_game_variant_parameter_haven_defender_personal_gravity,
	_game_variant_parameter_haven_defender_vehicle_use,
	_game_variant_parameter_haven_defender_motion_tracker,
	_game_variant_parameter_haven_defender_motion_tracker_range,
	_game_variant_parameter_haven_defender_waypoint,
	_game_variant_parameter_haven_defender_active_camo,
	_game_variant_parameter_haven_defender_visual,
	_game_variant_parameter_haven_defender_forced_change_colors,

	_game_variant_parameter_last_human_shield_damage_resistance,
	_game_variant_parameter_last_human_shield_multiplier,
	_game_variant_parameter_last_human_shield_recharge_rate,
	_game_variant_parameter_last_human_headshot_immunity,
	_game_variant_parameter_last_human_vampirism,
	_game_variant_parameter_last_human_damage_modifier_percentage,
	_game_variant_parameter_last_human_initial_primary_weapon,
	_game_variant_parameter_last_human_initial_secondary_weapon,
	_game_variant_parameter_last_human_initial_grenade_count,
	_game_variant_parameter_last_human_recharging_grenades,
	_game_variant_parameter_last_human_infinite_ammo,
	_game_variant_parameter_last_human_weapon_pickup,
	_game_variant_parameter_last_human_walking_speed,
	_game_variant_parameter_last_human_personal_gravity,
	_game_variant_parameter_last_human_vehicle_use,
	_game_variant_parameter_last_human_motion_tracker,
	_game_variant_parameter_last_human_motion_tracker_range,
	_game_variant_parameter_last_human_waypoint,
	_game_variant_parameter_last_human_active_camo,
	_game_variant_parameter_last_human_visual,
	_game_variant_parameter_last_human_forced_change_colors,

	_game_variant_parameter_king_opaque_hill,
	_game_variant_parameter_king_score_to_win,
	_game_variant_parameter_king_team_scoring,
	_game_variant_parameter_king_moving_hill,
	_game_variant_parameter_king_moving_hill_order,
	_game_variant_parameter_king_inside_hill_points,
	_game_variant_parameter_king_outside_hill_points,
	_game_variant_parameter_king_uncontested_hill_points,
	_game_variant_parameter_king_kill_points,

	_game_variant_parameter_in_hill_shield_damage_resistance,
	_game_variant_parameter_in_hill_shield_multiplier,
	_game_variant_parameter_in_hill_shield_recharge_rate,
	_game_variant_parameter_in_hill_headshot_immunity,
	_game_variant_parameter_in_hill_vampirism,
	_game_variant_parameter_in_hill_damage_modifier_percentage,
	_game_variant_parameter_in_hill_initial_primary_weapon,
	_game_variant_parameter_in_hill_initial_secondary_weapon,
	_game_variant_parameter_in_hill_initial_grenade_count,
	_game_variant_parameter_in_hill_recharging_grenades,
	_game_variant_parameter_in_hill_infinite_ammo,
	_game_variant_parameter_in_hill_weapon_pickup,
	_game_variant_parameter_in_hill_walking_speed,
	_game_variant_parameter_in_hill_personal_gravity,
	_game_variant_parameter_in_hill_vehicle_use,
	_game_variant_parameter_in_hill_motion_tracker,
	_game_variant_parameter_in_hill_motion_tracker_range,
	_game_variant_parameter_in_hill_waypoint,
	_game_variant_parameter_in_hill_active_camo,
	_game_variant_parameter_in_hill_visual,
	_game_variant_parameter_in_hill_forced_change_colors,

	_game_variant_parameter_territories_capture_time,
	_game_variant_parameter_territories_one_sided,
	_game_variant_parameter_territories_lock_after_capture,
	_game_variant_parameter_territories_sudden_death,
	_game_variant_parameter_territories_respawn_on_capture,

	_game_variant_parameter_territory_defender_shield_damage_resistance,
	_game_variant_parameter_territory_defender_shield_multiplier,
	_game_variant_parameter_territory_defender_shield_recharge_rate,
	_game_variant_parameter_territory_defender_headshot_immunity,
	_game_variant_parameter_territory_defender_vampirism,
	_game_variant_parameter_territory_defender_damage_modifier_percentage,
	_game_variant_parameter_territory_defender_initial_primary_weapon,
	_game_variant_parameter_territory_defender_initial_secondary_weapon,
	_game_variant_parameter_territory_defender_initial_grenade_count,
	_game_variant_parameter_territory_defender_recharging_grenades,
	_game_variant_parameter_territory_defender_infinite_ammo,
	_game_variant_parameter_territory_defender_weapon_pickup,
	_game_variant_parameter_territory_defender_walking_speed,
	_game_variant_parameter_territory_defender_personal_gravity,
	_game_variant_parameter_territory_defender_vehicle_use,
	_game_variant_parameter_territory_defender_motion_tracker,
	_game_variant_parameter_territory_defender_motion_tracker_range,
	_game_variant_parameter_territory_defender_waypoint,
	_game_variant_parameter_territory_defender_active_camo,
	_game_variant_parameter_territory_defender_visual,
	_game_variant_parameter_territory_defender_forced_change_colors,

	_game_variant_parameter_territory_attacker_shield_damage_resistance,
	_game_variant_parameter_territory_attacker_shield_multiplier,
	_game_variant_parameter_territory_attacker_shield_recharge_rate,
	_game_variant_parameter_territory_attacker_headshot_immunity,
	_game_variant_parameter_territory_attacker_vampirism,
	_game_variant_parameter_territory_attacker_damage_modifier_percentage,
	_game_variant_parameter_territory_attacker_initial_primary_weapon,
	_game_variant_parameter_territory_attacker_initial_secondary_weapon,
	_game_variant_parameter_territory_attacker_initial_grenade_count,
	_game_variant_parameter_territory_attacker_recharging_grenades,
	_game_variant_parameter_territory_attacker_infinite_ammo,
	_game_variant_parameter_territory_attacker_weapon_pickup,
	_game_variant_parameter_territory_attacker_walking_speed,
	_game_variant_parameter_territory_attacker_personal_gravity,
	_game_variant_parameter_territory_attacker_vehicle_use,
	_game_variant_parameter_territory_attacker_motion_tracker,
	_game_variant_parameter_territory_attacker_motion_tracker_range,
	_game_variant_parameter_territory_attacker_waypoint,
	_game_variant_parameter_territory_attacker_active_camo,
	_game_variant_parameter_territory_attacker_visual,
	_game_variant_parameter_territory_attacker_forced_change_colors,

	_game_variant_parameter_vip_score_to_win,
	_game_variant_parameter_vip_single_vip,
	_game_variant_parameter_vip_destination_zones_enabled,
	_game_variant_parameter_vip_end_round_on_vip_death,
	_game_variant_parameter_vip_kill_points,
	_game_variant_parameter_vip_takedown_points,
	_game_variant_parameter_vip_kill_as_vip_points,
	_game_variant_parameter_vip_death_points,
	_game_variant_parameter_vip_zone_arrival_points,
	_game_variant_parameter_vip_suicide_points,
	_game_variant_parameter_vip_vip_friendly_death_points,
	_game_variant_parameter_vip_betrayal_points,
	_game_variant_parameter_vip_selection,
	_game_variant_parameter_vip_zone_movement,
	_game_variant_parameter_vip_zone_order,
	_game_variant_parameter_vip_influence_radius,

	_game_variant_parameter_vip_team_shield_damage_resistance,
	_game_variant_parameter_vip_team_shield_multiplier,
	_game_variant_parameter_vip_team_shield_recharge_rate,
	_game_variant_parameter_vip_team_headshot_immunity,
	_game_variant_parameter_vip_team_vampirism,
	_game_variant_parameter_vip_team_damage_modifier_percentage,
	_game_variant_parameter_vip_team_initial_primary_weapon,
	_game_variant_parameter_vip_team_initial_secondary_weapon,
	_game_variant_parameter_vip_team_initial_grenade_count,
	_game_variant_parameter_vip_team_recharging_grenades,
	_game_variant_parameter_vip_team_infinite_ammo,
	_game_variant_parameter_vip_team_weapon_pickup,
	_game_variant_parameter_vip_team_walking_speed,
	_game_variant_parameter_vip_team_personal_gravity,
	_game_variant_parameter_vip_team_vehicle_use,
	_game_variant_parameter_vip_team_motion_tracker,
	_game_variant_parameter_vip_team_motion_tracker_range,
	_game_variant_parameter_vip_team_waypoint,
	_game_variant_parameter_vip_team_active_camo,
	_game_variant_parameter_vip_team_visual,
	_game_variant_parameter_vip_team_forced_change_colors,

	_game_variant_parameter_vip_influence_shield_damage_resistance,
	_game_variant_parameter_vip_influence_shield_multiplier,
	_game_variant_parameter_vip_influence_shield_recharge_rate,
	_game_variant_parameter_vip_influence_headshot_immunity,
	_game_variant_parameter_vip_influence_vampirism,
	_game_variant_parameter_vip_influence_damage_modifier_percentage,
	_game_variant_parameter_vip_influence_initial_primary_weapon,
	_game_variant_parameter_vip_influence_initial_secondary_weapon,
	_game_variant_parameter_vip_influence_initial_grenade_count,
	_game_variant_parameter_vip_influence_recharging_grenades,
	_game_variant_parameter_vip_influence_infinite_ammo,
	_game_variant_parameter_vip_influence_weapon_pickup,
	_game_variant_parameter_vip_influence_walking_speed,
	_game_variant_parameter_vip_influence_personal_gravity,
	_game_variant_parameter_vip_influence_vehicle_use,
	_game_variant_parameter_vip_influence_motion_tracker,
	_game_variant_parameter_vip_influence_motion_tracker_range,
	_game_variant_parameter_vip_influence_waypoint,
	_game_variant_parameter_vip_influence_active_camo,
	_game_variant_parameter_vip_influence_visual,
	_game_variant_parameter_vip_influence_forced_change_colors,

	_game_variant_parameter_vip_shield_damage_resistance,
	_game_variant_parameter_vip_shield_multiplier,
	_game_variant_parameter_vip_shield_recharge_rate,
	_game_variant_parameter_vip_headshot_immunity,
	_game_variant_parameter_vip_vampirism,
	_game_variant_parameter_vip_damage_modifier_percentage,
	_game_variant_parameter_vip_initial_primary_weapon,
	_game_variant_parameter_vip_initial_secondary_weapon,
	_game_variant_parameter_vip_initial_grenade_count,
	_game_variant_parameter_vip_recharging_grenades,
	_game_variant_parameter_vip_infinite_ammo,
	_game_variant_parameter_vip_weapon_pickup,
	_game_variant_parameter_vip_walking_speed,
	_game_variant_parameter_vip_personal_gravity,
	_game_variant_parameter_vip_vehicle_use,
	_game_variant_parameter_vip_motion_tracker,
	_game_variant_parameter_vip_motion_tracker_range,
	_game_variant_parameter_vip_waypoint,
	_game_variant_parameter_vip_active_camo,
	_game_variant_parameter_vip_visual,
	_game_variant_parameter_vip_forced_change_colors,

	_game_variant_parameter_juggernaut_score_to_win,
	_game_variant_parameter_juggernaut_kill_points,
	_game_variant_parameter_juggernaut_kill_juggernaut_poins,
	_game_variant_parameter_juggernaut_kill_as_juggernaut_points,
	_game_variant_parameter_juggernaut_zone_arrival_points,
	_game_variant_parameter_juggernaut_suicide_points,
	_game_variant_parameter_juggernaut_betrayal_points,
	_game_variant_parameter_juggernaut_initial_juggernaut,
	_game_variant_parameter_juggernaut_next_juggernaut,
	_game_variant_parameter_juggernaut_allied_against_juggernaut,
	_game_variant_parameter_juggernaut_delay,
	_game_variant_parameter_juggernaut_zones_enabled,
	_game_variant_parameter_juggernaut_zone_movement,
	_game_variant_parameter_juggernaut_zone_order,
	_game_variant_parameter_juggernaut_respawn_on_lone_juggernaut,
	_game_variant_parameter_juggernaut_shield_damage_resistance,
	_game_variant_parameter_juggernaut_shield_multiplier,
	_game_variant_parameter_juggernaut_shield_recharge_rate,
	_game_variant_parameter_juggernaut_headshot_immunity,
	_game_variant_parameter_juggernaut_vampirism,
	_game_variant_parameter_juggernaut_damage_modifier_percentage,
	_game_variant_parameter_juggernaut_initial_primary_weapon,
	_game_variant_parameter_juggernaut_initial_secondary_weapon,
	_game_variant_parameter_juggernaut_initial_grenade_count,
	_game_variant_parameter_juggernaut_recharging_grenades,
	_game_variant_parameter_juggernaut_infinite_ammo,
	_game_variant_parameter_juggernaut_weapon_pickup,
	_game_variant_parameter_juggernaut_walking_speed,
	_game_variant_parameter_juggernaut_personal_gravity,
	_game_variant_parameter_juggernaut_vehicle_use,
	_game_variant_parameter_juggernaut_motion_tracker,
	_game_variant_parameter_juggernaut_motion_tracker_range,
	_game_variant_parameter_juggernaut_waypoint,
	_game_variant_parameter_juggernaut_active_camo,
	_game_variant_parameter_juggernaut_visual,
	_game_variant_parameter_juggernaut_forced_change_colors,

	_game_variant_parameter_assault_arming_shield_damage_resistance,
	_game_variant_parameter_assault_arming_shield_multiplier,
	_game_variant_parameter_assault_arming_shield_recharge_rate,
	_game_variant_parameter_assault_arming_headshot_immunity,
	_game_variant_parameter_assault_arming_vampirism,
	_game_variant_parameter_assault_arming_damage_modifier_percentage,
	_game_variant_parameter_assault_arming_initial_primary_weapon,
	_game_variant_parameter_assault_arming_initial_secondary_weapon,
	_game_variant_parameter_assault_arming_initial_grenade_count,
	_game_variant_parameter_assault_arming_recharging_grenades,
	_game_variant_parameter_assault_arming_infinite_ammo,
	_game_variant_parameter_assault_arming_weapon_pickup,
	_game_variant_parameter_assault_arming_walking_speed,
	_game_variant_parameter_assault_arming_personal_gravity,
	_game_variant_parameter_assault_arming_vehicle_use,
	_game_variant_parameter_assault_arming_motion_tracker,
	_game_variant_parameter_assault_arming_motion_tracker_range,
	_game_variant_parameter_assault_arming_waypoint,
	_game_variant_parameter_assault_arming_active_camo,
	_game_variant_parameter_assault_arming_visual,
	_game_variant_parameter_assault_arming_forced_change_colors,

	_game_variant_parameter_assault_bomb_arming_time,
	_game_variant_parameter_assault_bomb_disarming_time,
	_game_variant_parameter_assault_bomb_fuse_time,
	_game_variant_parameter_assault_bomb_reset_time,

	_game_variant_parameter_assault_carrier_shield_damage_resistance,
	_game_variant_parameter_assault_carrier_shield_multiplier,
	_game_variant_parameter_assault_carrier_shield_recharge_rate,
	_game_variant_parameter_assault_carrier_headshot_immunity,
	_game_variant_parameter_assault_carrier_vampirism,
	_game_variant_parameter_assault_carrier_damage_modifier_percentage,
	_game_variant_parameter_assault_carrier_initial_primary_weapon,
	_game_variant_parameter_assault_carrier_initial_secondary_weapon,
	_game_variant_parameter_assault_carrier_initial_grenade_count,
	_game_variant_parameter_assault_carrier_recharging_grenades,
	_game_variant_parameter_assault_carrier_infinite_ammo,
	_game_variant_parameter_assault_carrier_weapon_pickup,
	_game_variant_parameter_assault_carrier_walking_speed,
	_game_variant_parameter_assault_carrier_personal_gravity,
	_game_variant_parameter_assault_carrier_vehicle_use,
	_game_variant_parameter_assault_carrier_motion_tracker,
	_game_variant_parameter_assault_carrier_motion_tracker_range,
	_game_variant_parameter_assault_carrier_waypoint,
	_game_variant_parameter_assault_carrier_active_camo,
	_game_variant_parameter_assault_carrier_visual,
	_game_variant_parameter_assault_carrier_forced_change_colors,
	_game_variant_parameter_assault_enemy_bomb_waypoint,
	_game_variant_parameter_assault_game_type,
	_game_variant_parameter_assault_reset_bomb_on_disarm,
	_game_variant_parameter_assault_siege_mode,
	_game_variant_parameter_assault_respawn,
	_game_variant_parameter_assault_score_to_win,
	_game_variant_parameter_assault_unknown577,
	_game_variant_parameter_assault_unknown578,
	_game_variant_parameter_assault_unknown579,
	_game_variant_parameter_assault_sudden_death_time,

	_game_variant_parameter_sandbox_open_voice_channel,
	_game_variant_parameter_sandbox_enter_editor_mode,
	_game_variant_parameter_sandbox_respawn_time,
	_game_variant_parameter_sandbox_editor_shield_damage_resistance,
	_game_variant_parameter_sandbox_editor_shield_multiplier,
	_game_variant_parameter_sandbox_editor_shield_recharge_rate,
	_game_variant_parameter_sandbox_editor_headshot_immunity,
	_game_variant_parameter_sandbox_editor_vampirism,
	_game_variant_parameter_sandbox_editor_damage_modifier_percentage,
	_game_variant_parameter_sandbox_editor_initial_primary_weapon,
	_game_variant_parameter_sandbox_editor_initial_secondary_weapon,
	_game_variant_parameter_sandbox_editor_initial_grenade_count,
	_game_variant_parameter_sandbox_editor_recharging_grenades,
	_game_variant_parameter_sandbox_editor_infinite_ammo,
	_game_variant_parameter_sandbox_editor_weapon_pickup,
	_game_variant_parameter_sandbox_editor_walking_speed,
	_game_variant_parameter_sandbox_editor_personal_gravity,
	_game_variant_parameter_sandbox_editor_vehicle_use,
	_game_variant_parameter_sandbox_editor_motion_tracker,
	_game_variant_parameter_sandbox_editor_motion_tracker_range,
	_game_variant_parameter_sandbox_editor_waypoint,
	_game_variant_parameter_sandbox_editor_active_camo,
	_game_variant_parameter_sandbox_editor_visual,
	_game_variant_parameter_sandbox_editor_forced_change_colors,

	_game_variant_parameter_template_shield_damage_resistance,
	_game_variant_parameter_template_shield_multiplier,
	_game_variant_parameter_template_shield_recharge_rate,
	_game_variant_parameter_template_headshot_immunity,
	_game_variant_parameter_template_vampirism,
	_game_variant_parameter_template_damage_modifier_percentage,
	_game_variant_parameter_template_initial_primary_weapon,
	_game_variant_parameter_template_initial_secondary_weapon,
	_game_variant_parameter_template_initial_grenade_count,
	_game_variant_parameter_template_recharging_grenades,
	_game_variant_parameter_template_infinite_ammo,
	_game_variant_parameter_template_weapon_pickup,
	_game_variant_parameter_template_walking_speed,
	_game_variant_parameter_template_personal_gravity,
	_game_variant_parameter_template_vehicle_use,
	_game_variant_parameter_template_motion_tracker,
	_game_variant_parameter_template_motion_tracker_range,
	_game_variant_parameter_template_waypoint,
	_game_variant_parameter_template_active_camo,
	_game_variant_parameter_template_visual,
	_game_variant_parameter_template_forced_change_colors,

	k_game_variant_parameter_count,
	k_game_variant_parameter_none = -1,
};

enum e_text_value_pair_parameter_type
{
	_text_value_pair_parameter_type_integer = 0,
	_text_value_pair_parameter_type_string_id,
	_text_value_pair_parameter_type_real_range,

	k_text_value_pair_parameter_type_count
};

enum e_game_content_type
{
	_game_content_type_dlcmap = 0,
	_game_content_type_usermap,
	_game_content_type_personal,
	_game_content_type_ctf,
	_game_content_type_slayer,
	_game_content_type_oddball,
	_game_content_type_king,
	_game_content_type_juggernaut,
	_game_content_type_territories,
	_game_content_type_assault,
	_game_content_type_vip,
	_game_content_type_infection,
	_game_content_type_film,
	_game_content_type_clip,
	_game_content_type_screenshot,

	k_number_of_game_content_types
};

enum e_quality_setting
{
	_quality_setting_low = 0,
	_quality_setting_medium,
	_quality_setting_high,

	k_quality_setting_count
};

enum e_subtitle_setting
{
	_subtitle_setting_automatic = 0,
	_subtitle_setting_enabled,
	_subtitle_setting_disabled,

	k_number_of_subtitle_settings
};

enum e_color_type
{
	_color_type_primary = 0,
	_color_type_secondary,
	_color_type_visor,
	_color_type_lights,
	_color_type_holo,

	k_color_type_count
};

enum e_armor_type
{
	_armor_type_helmet = 0,
	_armor_type_chest,
	_armor_type_shoulders,
	_armor_type_arms,
	_armor_type_legs,

	_armor_type_acc,
	_armor_type_pelvis,

	_armor_type_unknown7,
	_armor_type_unknown8,
	_armor_type_unknown9,

	k_armor_type_count
};

enum e_grenade_type
{
	_grenade_type_human_fragmentation = 0,
	_grenade_type_covenant_plasma,
	_grenade_type_brute_claymore,
	_grenade_type_firebomb,

	k_grenade_type_count
};

// `0069C3D0`, gameplay_modifier_get_name
// `0069C730`, gameplay_modifier_get_index
enum e_gameplay_modifier
{
	_gameplay_modifier_safety_booster = 0,
	_gameplay_modifier_explosives_damage,
	_gameplay_modifier_explosives_aoe_size_boost,
	_gameplay_modifier_grenade_scavenger,
	_gameplay_modifier_stamina_restore_near_death,
	_gameplay_modifier_cooldown_reset,
	_gameplay_modifier_reflex_boost,
	_gameplay_modifier_zoom_radar,
	_gameplay_modifier_cooldown_boost,
	_gameplay_modifier_enable_nemesis_mechanics,
	_gameplay_modifier_silent_sprint,
	_gameplay_modifier_vehicle_shield_regen_speed,
	_gameplay_modifier_vehicle_shield_regen_delay,
	_gameplay_modifier_scavenger_aura,
	_gameplay_modifier_armor_to_vehicle,
	_gameplay_modifier_armor_to_player_in_vehicle,
	_gameplay_modifier_armor_to_player_in_vehicle_transferred,
	_gameplay_modifier_sprint_speed,
	_gameplay_modifier_sprint_stamina,
	_gameplay_modifier_reload_speed,
	_gameplay_modifier_weapon_switch_speed,
	_gameplay_modifier_ammo_max,
	_gameplay_modifier_melee_damage,
	_gameplay_modifier_melee_resist,
	_gameplay_modifier_revenge_shield_boost,
	_gameplay_modifier_respawn_modifier,
	_gameplay_modifier_grenades_max,
	_gameplay_modifier_motion_sensor_range,
	_gameplay_modifier_shield_regen_rate,
	_gameplay_modifier_shield_regen_delay,
	_gameplay_modifier_teflon_armor,
	_gameplay_modifier_explosion_resist,
	_gameplay_modifier_vehicle_ram_damage,
	_gameplay_modifier_turret_damage,
	_gameplay_modifier_machine_gun_rof_acceleration_time,
	_gameplay_modifier_grenade_warning,
	_gameplay_modifier_consumable_duration,
	_gameplay_modifier_energy_increase_max,
	_gameplay_modifier_energy_increase_count_on_spawn,
	_gameplay_modifier_energy_regeneration_rate,
	_gameplay_modifier_assault_rifle_rounds_per_second,
	_gameplay_modifier_assault_rifle_damage,
	_gameplay_modifier_assault_rifle_ammo_capacity,
	_gameplay_modifier_assault_rifle_reload_speed,
	_gameplay_modifier_battle_rifle_rounds_per_second,
	_gameplay_modifier_battle_rifle_fire_recovery_time,
	_gameplay_modifier_battle_rifle_damage,
	_gameplay_modifier_battle_rifle_ammo_capacity,
	_gameplay_modifier_battle_rifle_reload_speed,
	_gameplay_modifier_shotgun_spread,
	_gameplay_modifier_shotgun_damage,
	_gameplay_modifier_shotgun_ammo_capacity,
	_gameplay_modifier_shotgun_reload_speed,
	_gameplay_modifier_sniper_rifle_zoom_protection,
	_gameplay_modifier_sniper_rifle_damage,
	_gameplay_modifier_sniper_rifle_ammo_capacity,
	_gameplay_modifier_sniper_rifle_reload_speed,
	_gameplay_modifier_dmr_zoom_protection,
	_gameplay_modifier_dmr_damage,
	_gameplay_modifier_dmr_ammo_capacity,
	_gameplay_modifier_dmr_reload_speed,
	_gameplay_modifier_magnum_rounds_per_second,
	_gameplay_modifier_magnum_penetration,
	_gameplay_modifier_magnum_accuracy,
	_gameplay_modifier_magnum_damage,
	_gameplay_modifier_magnum_ammo_capacity,
	_gameplay_modifier_magnum_reload_speed,
	_gameplay_modifier_plasma_pistol_charge_up_time,
	_gameplay_modifier_plasma_pistol_damage,
	_gameplay_modifier_plasma_pistol_ammo_capacity,
	_gameplay_modifier_plasma_pistol_heat_per_round,
	_gameplay_modifier_frag_grenade_aoe_size,
	_gameplay_modifier_frag_grenade_damage,
	_gameplay_modifier_frag_grenade_ammo_capacity,
	_gameplay_modifier_plasma_grenade_aoe_size,
	_gameplay_modifier_plasma_grenade_damage,
	_gameplay_modifier_plasma_grenade_ammo_capacity,
	_gameplay_modifier_mauler_damage,
	_gameplay_modifier_spiker_damage,
	_gameplay_modifier_brute_shot_damage,
	_gameplay_modifier_plasma_rifle_heat_per_round,
	_gameplay_modifier_detonate_on_player_cdt,
	_gameplay_modifier_detonate_on_vehicle_cdt,
	_gameplay_modifier_enemies_always_on_radar,
	_gameplay_modifier_plant_plasma_on_death,
	_gameplay_modifier_shield_regen_rate_near_killed_enemies,
	_gameplay_modifier_shield_recharge_on_melee_kill,
	_gameplay_modifier_frag_grenades_max,
	_gameplay_modifier_plasma_grenades_max,
	_gameplay_modifier_claymore_grenade_aoe_size,
	_gameplay_modifier_smg_damage,
	_gameplay_modifier_smg_reload_speed,
	_gameplay_modifier_vehicle_autoflip,

	k_gameplay_modifier_count
};

enum e_player_respawn_failure
{
	_player_respawn_failure_none = 0,
	_player_respawn_failure_in_editor,
	_player_respawn_failure_cinematic_playing,
	_player_respawn_failure_scripting_says_it_isnt_safe,
	_player_respawn_failure_waiting_on_respawn_timer,
	_player_respawn_failure_friend_in_combat,
	_player_respawn_failure_nearby_enemies_pursuing_friend,
	_player_respawn_failure_friend_airborne_or_moving,
	_player_respawn_failure_friend_in_vehicle,
	_player_respawn_failure_everybody_is_dead,
	_player_respawn_failure_waiting_for_checkpoint,
	_player_respawn_failure_can_not_find_valid_location,

	k_player_respawn_failure_count
};

enum e_multiplayer_powerup_flavor
{
	_multiplayer_powerup_flavor_none = -1,
	_multiplayer_powerup_flavor_red,
	_multiplayer_powerup_flavor_blue,
	_multiplayer_powerup_flavor_yellow,

	k_number_of_multiplayer_powerup_flavors
};

enum e_shell_application_type
{
	_shell_application_type_none = 0,
	_shell_application_type_editor,
	_shell_application_type_client,
};

enum e_shell_tool_type
{
	_shell_tool_type_none = 0,
	_shell_tool_type_guerilla,
	_shell_tool_type_tool,
};

enum e_init_file_type
{
	_init_file_type_editor = 0,
	_init_file_type_bonobo,
};

enum e_campaign_team
{
	_campaign_team_default = 0,
	_campaign_team_player,
	_campaign_team_human,
	_campaign_team_covenant,
	_campaign_team_flood,
	_campaign_team_sentinel,
	_campaign_team_heretic,
	_campaign_team_prophet,
	_campaign_team_guilty,
	_campaign_team_unused9,
	_campaign_team_unused10,
	_campaign_team_unused11,
	_campaign_team_unused12,
	_campaign_team_unused13,
	_campaign_team_unused14,
	_campaign_team_unused15,

	k_number_of_campaign_teams
};

enum e_multiplayer_team
{
	_multiplayer_team_red = 0,
	_multiplayer_team_blue,
	_multiplayer_team_green,
	_multiplayer_team_yellow,
	_multiplayer_team_purple,
	_multiplayer_team_orange,
	_multiplayer_team_brown,
	_multiplayer_team_grey,

	k_number_of_multiplayer_teams
};

enum e_button_preset
{
	_button_preset_standard = 0,
	_button_preset_south_paw,
	_button_preset_boxer,
	_button_preset_green_thumb,
	_button_preset_professional,
	_button_preset_walkie_talkie,

	k_number_of_button_presets
};

enum e_joystick_preset
{
	_joystick_preset_standard = 0,
	_joystick_preset_south_paw,
	_joystick_preset_legacy,
	_joystick_preset_legacy_south_paw,

	k_number_of_joystick_presets
};

enum e_voice_output_setting
{
	_voice_output_setting_default = 0,
	_voice_output_setting_headset,

	k_number_of_voice_output_settings
};

enum e_voice_mask
{
	_voice_mask_none = 0,
	_voice_mask_anonymous,

	k_number_of_voice_masks
};

enum e_actor_type
{
	_actor_elite = 0,
	_actor_jackal,
	_actor_grunt,
	_actor_hunter,
	_actor_engineer,
	_actor_assassin,
	_actor_player,
	_actor_marine,
	_actor_crew,
	_actor_combat_form,
	_actor_infection_form,
	_actor_carrier_form,
	_actor_monitor,
	_actor_sentinel,
	_actor_none,
	_actor_mounted_weapon,
	_actor_brute,
	_actor_prophet,
	_actor_bugger,
	_actor_juggernaut,
	_actor_pure_form_stealth,
	_actor_pure_form_tank,
	_actor_pure_form_ranged,
	_actor_scarab,
	_actor_guardian,

	k_number_of_actor_types
};

enum e_model_state
{
	_model_state_standard = 0,
	_model_state_minor_damage,
	_model_state_medium_damage,
	_model_state_major_damage,
	_model_state_destroyed,

	k_number_of_model_states
};

enum e_character_physics_override
{
	_character_physics_override_none = 0,
	_character_physics_override_player,
	_character_physics_override_biped,

	k_number_of_character_physics_overrides
};

enum e_ai_sound_volume
{
	_ai_sound_volume_silent = 0,
	_ai_sound_volume_medium,
	_ai_sound_volume_loud,
	_ai_sound_volume_shout,
	_ai_sound_volume_quiet,

	k_ai_sound_volume_count
};

enum e_game_engine_status_flags
{
	_game_engine_status_flags_unused_bit = 0,

	k_game_engine_status_flags
};

enum e_game_engine_status
{
	_game_engine_status_waiting_for_space_to_clear = 0,
	_game_engine_status_observing,
	_game_engine_status_respawning_soon,
	_game_engine_status_sitting_out,
	_game_engine_status_out_of_lives,
	_game_engine_status_playing_winning,
	_game_engine_status_playing_tied,
	_game_engine_status_playing_losing,
	_game_engine_status_game_over_won,
	_game_engine_status_game_over_tied,
	_game_engine_status_game_over_lost,
	_game_engine_status_game_over_you_lost_but_game_tied,
	_game_engine_status_you_have_flag,
	_game_engine_status_enemy_has_flag,
	_game_engine_status_flag_not_home,
	_game_engine_status_carrying_oddball,
	_game_engine_status_you_are_juggy,
	_game_engine_status_you_control_hill,
	_game_engine_status_switching_sides_soon,
	_game_engine_status_player_recently_started,
	_game_engine_status_you_have_bomb,
	_game_engine_status_flag_contested,
	_game_engine_status_bomb_contested,
	_game_engine_status_limited_lives_left_multiple,
	_game_engine_status_limited_lives_left_single,
	_game_engine_status_limited_lives_left_final,
	_game_engine_status_playing_winning_unlimited,
	_game_engine_status_playing_tied_unlimited,
	_game_engine_status_playing_losing_unlimited,

	// HO?
	_game_engine_status_in_lobby,

	k_game_engine_status_count
};

enum e_odst_recon_variant
{
	_odst_recon_variant_none = 0,
	_odst_recon_variant_rookie,
	_odst_recon_variant_buck,
	_odst_recon_variant_dare,
	_odst_recon_variant_dutch,
	_odst_recon_variant_johnson,
	_odst_recon_variant_mickey,
	_odst_recon_variant_romeo,

	k_odst_recon_variant_count
};

enum e_user_interface_sound_effect
{
	_user_interface_sound_effect_error = 0,
	_user_interface_sound_effect_vertical_navigation,
	_user_interface_sound_effect_horizontal_navigation,
	_user_interface_sound_effect_a_button,
	_user_interface_sound_effect_b_button,
	_user_interface_sound_effect_x_button,
	_user_interface_sound_effect_y_button,
	_user_interface_sound_effect_start_button,
	_user_interface_sound_effect_back_button,
	_user_interface_sound_effect_left_bumper,
	_user_interface_sound_effect_right_bumper,
	_user_interface_sound_effect_left_trigger,
	_user_interface_sound_effect_right_trigger,
	_user_interface_sound_effect_timer_sound,
	_user_interface_sound_effect_timer_sound_zero,
	_user_interface_sound_effect_alt_timer_sound,
	_user_interface_sound_effect_second_alt_timer,
	_user_interface_sound_effect_matchmaking_advance,
	_user_interface_sound_effect_rank_up,
	_user_interface_sound_effect_matchmaking_party_up,

	k_user_interface_sound_effect_count
};

//e_network_interface_user_state
// none
// local user exists
// local user is zombie
// player not online enabled
// user content not allowed
// failed generic
// in matchmaking
// film in progress
// campaign in progress
// session full
// alpha split screen
// no profile sent to main menu
// not signed in bring up guide
// confirm the use of a temporary account
// survival in progress

extern bool __cdecl shell_application_is_paused();
extern void __cdecl shell_application_pause(bool pause);
extern e_shell_application_type __cdecl shell_application_type();
extern bool __cdecl shell_build_number_is_compatible(long build_number);
extern bool __cdecl shell_build_string_is_compatible(char const* build_string);
extern void __cdecl shell_dispose();
extern char const* __cdecl shell_get_target();
extern char const* __cdecl shell_get_target_variant();
extern void __cdecl shell_halt_on_pure_virtual_call();
extern void __cdecl shell_halt_with_message(char const* message);
extern bool __cdecl shell_initialize(bool windowed);
extern bool __cdecl game_is_bot_client();
extern bool __cdecl game_is_dedicated_server();
extern bool __cdecl game_is_client();
extern bool __cdecl game_is_guerilla();
extern bool __cdecl game_is_halo3();
extern bool __cdecl game_is_sapien();
extern bool __cdecl game_is_tool();
extern e_shell_tool_type __cdecl shell_tool_type();

extern char const* quality_setting_get_name(e_quality_setting quality_setting);
extern e_quality_setting quality_setting_from_string(char const* str);
extern char const* subtitle_setting_get_name(e_subtitle_setting subtitle_setting);
extern e_subtitle_setting subtitle_setting_from_string(char const* str);
extern char const* campaign_difficulty_level_get_name(e_campaign_difficulty_level difficulty);
extern e_campaign_difficulty_level campaign_difficulty_level_from_string(char const* str);
extern char const* network_session_mode_get_name(long session_mode);
extern char const* ui_game_mode_get_name(long ui_game_mode);
extern char const* gui_network_session_advertisement_mode_get_name(long advertisement_mode);
extern char const* game_variant_parameter_get_name(long parameter);

extern char const* const k_network_session_mode_names[k_network_session_mode_count];
extern char const* const k_ui_game_mode_names[k_ui_game_mode_count];
extern char const* const k_gui_network_session_advertisement_mode_names[k_gui_network_session_advertisement_mode_count];
extern char const* const k_game_variant_parameter_names[k_game_variant_parameter_count];
extern char const* const global_campaign_difficulty_level_names[k_number_of_campaign_difficulty_levels];
extern char const* const global_campaign_team_names[k_number_of_campaign_teams];
extern char const* const global_multiplayer_team_names[k_number_of_multiplayer_teams];
extern char const* const global_controller_index_names[k_number_of_controllers];
extern char const* const global_button_preset_names[k_number_of_button_presets];
extern char const* const global_joystick_preset_names[k_number_of_joystick_presets];
extern char const* const global_player_model_choice_names[k_number_of_player_model_choices];
extern char const* const global_voice_output_setting_names[k_number_of_voice_output_settings];
extern char const* const global_voice_mask_names[k_number_of_voice_masks];
extern char const* const global_subtitle_setting_names[k_number_of_subtitle_settings];
extern char const* const global_actor_type_names[k_number_of_actor_types];
extern char const* const global_model_state_names[k_number_of_model_states];
extern char const* const global_character_physics_override_names[k_number_of_character_physics_overrides];
extern char const* const global_primary_skull_names[k_number_of_primary_skulls];
extern char const* const global_secondary_skull_names[k_number_of_secondary_skulls];

