name: build

on:
  push:

jobs:
  build-win:
    strategy:
      matrix:
        BUILD_CONFIGURATION: [ 0_Tags, 1_Debug, 2_Test, 3_Play, 4_Profile, 5_Release ]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get CMake
      uses: lukka/get-cmake@v4.2.0
      with:
        cmakeVersion: 4.2.0

    - name: Initialize Submodules 
      uses: snickerbockers/submodules-init@v4

    - name: Determine Version
      id: determine_version
      run: |
        $version = (git rev-parse --short=7 HEAD).Trim()
        Write-Output "Version determined: $version"
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Configure CMake
      run: cmake -B build -S . -A Win32

    - name: Build
      run: cmake --build build --config ${{ matrix.BUILD_CONFIGURATION }}

    - name: Zip Release
      run: |
        7z a ${{ matrix.BUILD_CONFIGURATION }}.7z ./bin/${{ matrix.BUILD_CONFIGURATION }}/*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.BUILD_CONFIGURATION }}.7z
        tag_name: ${{ steps.determine_version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
